### ISSUE TITLE
"Only" not working without Array Syntax

### ISSUE THREAD

**Issue by RohitRox** [collectiveidea/audited#228]
When trying to audit one field, such as :name, there is an error. For example:

```
    audited only: :name 
```
leads to

.../audited-4.2.0/lib/audited/auditor.rb:46:in `audited': undefined method `flatten' for :note:Symbol (NoMethodError)

However, when wrapped in an array, it seems to work fine. For example: 

```
    audited only: [:name]
```
works fine.

The first style is in the official documentation. Is the first style broken?

**Comment by danielmorrison** [comment]
Great catch! It was broken. 

Fixed in [4.2-stable branch](https://github.com/collectiveidea/audited/tree/4.2-stable) and in master.

**Comment by RohitRox** [comment]
:+1:  :bow:

**Comment by manishkakwani** [comment]
Hi, I worked with RohitRox when we noticed the bug. It looks like the commit went into master on September 12th (https://github.com/collectiveidea/audited/commit/d66731241b8cd6cc1a7ce26dd6d5d9e59286e4d5nd ) but the last release, 4.2.0, went out in March. Has master been updated but a new, incremented release hasn't gone out since mid-September?

-Manish

**Comment by manishkakwani** [comment]
Sorry, the url for the commit is: https://github.com/collectiveidea/audited/commit/d66731241b8cd6cc1a7ce26dd6d5d9e59286e4d5
