### ISSUE TITLE
Set Username field in the audits while creation

### ISSUE THREAD

**Issue by seemalakishore** [collectiveidea/audited#271]
How can we set user name while creating audits. My application is built using rails_api gem. Though user management is done through devise, I could set the user_id value of logged in user using the below block:
`Audited.audit_class.as_user(logged_in_user) do
end `
I want to **set the username field as well during audit creation**, because finding username based on the user_id in each audit is cumbersome process while displaying, as it is not direct column and though database fetching should be done for each audit's username.

**Comment by seemalakishore** [comment]
@danielmorrison : Expecting a quick reply

**Comment by danielmorrison** [comment]
The way audited is currently built, we set either the `user_id` or the `username` but not both. This has come up before, but nobody has been excited enough to make the change. 

You would probably have to monkey-patch [`Audit#user_as_string=`](https://github.com/collectiveidea/audited/blob/master/lib/audited/audit.rb#L72) to have it set the username too.

**Comment by seemalakishore** [comment]
Thank you @danielmorrison

**Comment by cjmccormick88** [comment]
I'm having the same issue.  It is actually important that this gets fixed, I think, because one of the features I need in my application is a visible Audit Trail that can be accessed by users of the application to review the changes and who has committed them.  A number is not useful to them.  They need the username (a more tangible and understandable value); otherwise, every time an audit had to be done it would require running queries behind the scenes to determine the user's identity.

Since this issue may only matter for the actual view.....I wonder if a helper could not be employed.
