### ISSUE TITLE
Limit number of audits stored

### ISSUE THREAD

**Issue by jeremylynch** [collectiveidea/audited#274]
It would be handy if there was a way to store only a certain number of audits. Ie. delete the first audit once this number if reached. 

I am currently achieving this with the following code. 

``` ruby
def update_attributes_with_audits(case_params)
  update(case_params)
  audits_count = audits.count
  if audits_count >= 15
    audits.first.destroy
  end
end
```

**Comment by lacco** [comment]
I want to achieve something similar. I haven't looked into the exact details yet, but instead of just destroying old audits, I want to merge the changes in newer ones. I would move the logic in a daily cronjob and merge multiple ```update``` audits.

In case somebody has already a snippet for this, it would be helpful. I will also share my results here since it feels like that this might be related.

**Comment by fatkodima** [comment]
Hey guys, i've made a pull request for that - #405
