### ISSUE TITLE
user_id and user_type is nil

### ISSUE THREAD

**Issue by kalashnikovisme** [collectiveidea/audited#348]
Hello! Catched the issue:
Rails '5.0.2'
Ruby '2.4.0'

```ruby
class Approval < ApplicationRecord
  belongs_to :user
  belongs_to :assessment_assignment

  audited :on => :destroy
end
```

```ruby
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end
```

After destroy I have `Audit` object

```ruby
#<Audited::Audit:0x00000007ff30f0
 id: 26,
 auditable_id: 58,
 auditable_type: "Approval",
 associated_id: nil,
 associated_type: nil,
 user_id: nil,
 user_type: nil,
 username: "#<User:0x0000000644e430>",
 action: "destroy",
 audited_changes: {},
 version: 1,
 comment: nil,
 remote_address: "127.0.0.1",
 request_uuid: "66d819a0-e737-4828-abca-45a469b423e4",
 created_at: Fri, 05 May 2017 12:02:15 UTC +00:00>
```

I think that the issue because of this line in the `/lib/audited/audit.rb`

```ruby
self.user ||= ::Audited.store[:current_user].try!(:call)
```

https://github.com/collectiveidea/audited/blob/master/lib/audited/audit.rb#L161

`::Audited.store[:current_user]` returns `User` object. But `self.user` is just `String`

```ruby
    161:   self.user ||= ::Audited.store[:audited_user] # from .as_user
    162:   self.user ||= ::Audited.store[:current_user].try!(:call) # from Sweeper
    163:   binding.pry
    164:   nil # prevent stopping callback chains
    165: end
[1] pry(#<Audited::Audit>)> ::Audited.store[:current_user]
=> #<User id: 1261, first_name: "John", last_name: "Doe", ....>
[1] pry(#<Audited::Audit>)> self.user
=> "#<User:0x000000056c8680>"
[2] pry(#<Audited::Audit>)> self.user.class
=> String
```

what's wrong with it?
I think we can replace `self.user ||= ::Audited.store[:current_user].try!(:call)` with two lines

```ruby
self.user_id ||= ::Audited.store[:current_user].try!(:call).id
self.user_type ||= ::Audited.store[:current_user].try!(:call).class.name
```

I have tested it. It works.

**Comment by domcleal** [comment]
The `user` accessor on Audited::Audit is a little strange as it supports both strings and models, it's worth looking at the implementation: https://github.com/collectiveidea/audited/blob/v4.4.0/lib/audited/audit.rb#L89-L106. For this reason, replacing it with an id/type setter wouldn't be fully compatible. It might be that your issue has another cause, or the setter is buggy in some way.

Does your `User` model inherit from something other than `ActiveRecord::Base`? If so, then the setter will treat it as a string typed object, which may explain why `#<User:0x...>` is stored in the `username` attribute rather than with user_id/type.

**Comment by kalashnikovisme** [comment]
@domcleal yes, my model is inherit from `SimpleDelegator`.
What should I do with it?

**Comment by domcleal** [comment]
If this is an ActiveRecord-based application then you should probably return a real AR::Base model from the `current_user` method of your controller (or if that's inconvenient, you can choose a different method, see the README). Then the association will work properly, assigning `id` and `type`.

Otherwise I think you should return a string value which will be stored in the `username` field - you can put the username, an ID or similar in that field and use it as you wish.

I don't think Rails or audited can work reliably passing delegators into associations. Perhaps use the [dumb_delegator](https://github.com/stevenharman/dumb_delegator) gem instead if you absolutely have to?

**Comment by kalashnikovisme** [comment]
@domcleal sorry, I made mistake.
My `User` model is inherit of `ActiveRecord::Base` class.

**Comment by domcleal** [comment]
I don't see how that can be, if you look at the Audit#user= code linked above. Please add debug to show which code path it's taking.

1. What does `controller.current_user.is_a?(::ActiveRecord::Base)` return?
2. What does `Audit.new.tap { |a| a.user = controller.current_user }.inspect` return?

**Comment by kalashnikovisme** [comment]
@domcleal understood what should can I do.
Thanks!!!
Will close the issue after solving the problem.

**Comment by kalashnikovisme** [comment]
Problem was solved!

The reason of my problem was that `current_user` sometimes is `SimpleDelegator`, but sometimes is `User`
I've created new method

```ruby
def audited_user
  current_user&.underlying_user
end
```

and add to `User` and my `SimpleDelegator` decorator this methods

```ruby
class User
  # ...
  def underlying_user
    self
  end
end

class MySimpleDelegator < SimpleDelegator
  # ...
  def underlying_user
    __getobj__
  end
end
```

and add new method to audited initializer

```ruby
Audited.current_user_method = :audited_user
```

And Voila!!!
thanks @domcleal for help!!
Close the issue!

**Comment by madhusudhanmo** [comment]
@kalashnikovisme, @domcleal  I'm facing similar issue where user_id and user_type are not saved. I'm migrating rails app from 4.2.1 to 5.2.1 and audited version from 4.3.0 to 4.80. 

I've tried the above solution but still didn't work. As I checked this method is not called while saving the record https://github.com/collectiveidea/audited/blob/master/lib/audited/sweeper.rb#L20-L22, can you let me know what might be the issue.
