### ISSUE TITLE
[Idea] Filter option

### ISSUE THREAD

**Issue by ankane** [collectiveidea/audited#475]
Hi, I wanted to get your thoughts on an idea before putting together a PR.

It'd be nice to have a `filter` option for sensitive data that would record that a field was changed, but not the actual values. It could write something like `[FILTERED]` instead (like what Rails does for filtered parameters).

```ruby
class User
  audited filter: [:email, :phone]
end
```

Let me know what you think.

**Comment by tbrisker** [comment]
That would be a good idea, we have something similar in Foreman for password and encrypted fields (https://github.com/theforeman/foreman/blob/develop/app/models/concerns/audit_extensions.rb#L150-L167), and i even took a stab at it over a year ago - https://github.com/collectiveidea/audited/pull/339. It would be good to allow custom content to be recorded, since the fields may have different data types etc. (see the discussion on my old PR)

**Comment by ankane** [comment]
Ah, missed your PR (didn't search for `redacted`). Looks like the same idea. Any reason you decided to close it?

**Comment by tbrisker** [comment]
@ankane i didn't have the time to work on it to fix it properly

**Comment by ankane** [comment]
I'm not sure I understand the concern in the PR for different data types. It seems fine to record a `[REDACTED]` string no matter what the data type is. What am I missing?

**Comment by JonathanWThom** [comment]
Hello, I took a crack at this here > https://github.com/collectiveidea/audited/pull/485. Hope it's what you were looking for!

**Comment by ankane** [comment]
Thanks @JonathanWThom, haven't had a chance to try it yet, but looks super clean.

**Comment by aidandamerell** [comment]
Any movement on this?

**Comment by ankane** [comment]
Closing, as future discussion can happen in the PR
