### ISSUE TITLE
Why not store created_at and updated_at by default?

### ISSUE THREAD

**Issue by IanVaughan** [collectiveidea/audited#590]
Just curious as to why `created_at` and `updated_at` are not saved as default?
When I wanted to extract a revision, I only then noticed we have not been saving this data.
I guess I can include these via `audited only: []`, but then I need to also manually list all the other attributes.
What do you folks think about adding date fields as standard if present?

**Comment by danielmorrison** [comment]
`created_at` should never change, so it doesn't need to be there. 
`updated_at` usually ends up being the same as the audit itself (or close enough), so it seemed redundant. 

Since these are automatically managed, it didn't seem to add value to save them as audits. It (usually) isn't something you care to track. 

I'm not eager to add them, but would be open to ideas.

**Comment by IanVaughan** [comment]
Thanks for your reply...
Sorry for missing this completely, but of course, the `created_at` is within the first revision!
And yes, I see now that `updated_at` will be the destroy itself.
Thanks again for your time and for this gem!
